### ISSUE TITLE
pip3 install gnuvid ?

### ISSUE THREAD

**Issue by tseemann** [ahmedmagds/GNUVID#1]
If you want s/w to be packaged into brew and bioconda you need to get it into pypi first.

There are many guides on how to do this:

eg https://realpython.com/pypi-publish-python-package/

**Comment by ahmedmagds** [comment]
Sure, I will add this to my list to-do.

**Comment by ahmedmagds** [comment]
@tseemann I have now added GNUVID 2.0 to bioconda. This release uses a random forest classifier to classify the virus to our defined clonal complexes (using wgMLST approach).
